# Generated by Django 3.2.16 on 2024-05-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0002_alter_selldb_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selldb',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='registerdb',
            name='id',
        ),
        migrations.AddField(
            model_name='registerdb',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
