# Generated by Django 3.2.16 on 2024-05-29 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Frontend', '0003_auto_20240529_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='user_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Mobile',
            new_name='mobile',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Product_Image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='selldb',
            old_name='Product_Name',
            new_name='product_name',
        ),
        migrations.RemoveField(
            model_name='selldb',
            name='user_id',
        ),
        migrations.AddField(
            model_name='selldb',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
