# Generated by Django 3.2.16 on 2024-05-29 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Frontend', '0004_auto_20240529_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='selldb',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
