# Generated by Django 3.2.16 on 2024-05-29 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0007_alter_selldb_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registerdb',
            old_name='id',
            new_name='UserId',
        ),
        migrations.RemoveField(
            model_name='selldb',
            name='user',
        ),
        migrations.AddField(
            model_name='selldb',
            name='UserId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb'),
            preserve_default=False,
        ),
    ]
