# Generated by Django 4.2.13 on 2024-05-29 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0014_alter_selldb_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selldb',
            name='UserId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Frontend.registerdb'),
        ),
    ]
